# Generated by Django 5.2.5 on 2025-09-04 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratorMessages',
            fields=[
                ('cd_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('cd_session', models.BigIntegerField()),
                ('ds_text', models.TextField()),
                ('dt_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cd_identifier_client', models.BigIntegerField()),
                ('ds_identifier_user', models.CharField(max_length=255)),
                ('ds_platform', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OrchestratorMessages',
                'indexes': [models.Index(fields=['cd_id'], name='Orchestrato_cd_id_a801d9_idx')],
            },
        ),
    ]
