# Generated by Django 5.2.5 on 2025-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestratormessages',
            name='cd_identifier_client',
        ),
        migrations.AddField(
            model_name='orchestratormessages',
            name='ds_identifier_client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orchestratormessages',
            name='ds_identifier_user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
