# Generated by Django 5.2.5 on 2025-09-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_remove_orchestratormessages_cd_identifier_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orchestratormessages',
            old_name='ds_platform',
            new_name='ds_channel_name',
        ),
        migrations.RenameField(
            model_name='orchestratormessages',
            old_name='ds_identifier_client',
            new_name='ds_id_channel_user',
        ),
        migrations.RenameField(
            model_name='orchestratormessages',
            old_name='ds_identifier_user',
            new_name='ds_id_platform_user',
        ),
    ]
