# Generated by Django 5.2.5 on 2025-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_rename_ds_platform_orchestratormessages_ds_channel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMessagesReference',
            fields=[
                ('cd_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('ds_message', models.BigIntegerField()),
                ('ds_response', models.TextField()),
            ],
            options={
                'db_table': 'CommonMessages',
            },
        ),
        migrations.AddIndex(
            model_name='orchestratormessages',
            index=models.Index(fields=['ds_id_channel_user'], name='Orchestrato_ds_id_c_6ba1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='commonmessagesreference',
            index=models.Index(fields=['cd_id'], name='CommonMessa_cd_id_51d744_idx'),
        ),
    ]
