# Generated by Django 5.2.5 on 2025-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_commonmessagesreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmessagesreference',
            name='ds_message',
            field=models.TextField(),
        ),
    ]
